### DISCUSSION TITLE
Default execution layer port changed, how do I restore it?

### DISCUSSION THREAD

**Discussion by jaa2** [ethpandaops/ethereum-package#1035] [Q&A] [answered]
Hi, I have a simple Kurtosis config for launching a simple EL/CL network:

```yaml
participants:
  - el_type: geth
    cl_type: lighthouse
    count: 1
network_params:
  network_id: "30121"
  prefunded_accounts: '{"0x359Eeb0c3266007B1975CA7a399b6FBaB1122824": {"balance": "300ETH"}, "0x72A6CF1837105827077250171974056B40377488": {"balance": "999999ETH"}}'
port_publisher:
  el:
    enabled: true
    public_port_start: 32000
```

All my scripts connect to `http://localhost:32002` for the RPC, but recently this has no longer been working, and instead a metrics server is hosted on port 32002:

```
4e976f2e0fb6   el-1-geth-lighthouse                             engine-rpc: 8551/tcp -> 127.0.0.1:32001       RUNNING
                                                                metrics: 9001/tcp -> http://127.0.0.1:32002   
                                                                rpc: 8545/tcp -> 127.0.0.1:32003              
                                                                tcp-discovery: 32000/tcp -> 127.0.0.1:32000   
                                                                udp-discovery: 32000/udp -> 127.0.0.1:32000   
                                                                ws: 8546/tcp -> 127.0.0.1:32004               

```

How can I restore the geth RPC URL to use port 32002?
