### DISCUSSION TITLE
Blocked for new account creation.

### DISCUSSION THREAD

**Discussion by l0git3k** [ethpandaops/ethereum-package#750] [Q&A]
Hello,
I have set up a kurtosis instance with the settings below but I get stuck when I want to create accounts and transfer ETH.
I've tried using “clef” on a separate machine, but I haven't found a way to make it work with my nodes from Kurtosis. I've also tried using “clef” directly from an EL, again without success. When I create a new account with the “geth account new” command on an EL, the account is created but not visible in the JS console (eth.accounts).

I've managed to connect a metamask wallet via RPC to my EL but when I try to transfer funds between pre-funded accounts and my metamask wallet it tells me that the pre-funded account doesn't exist.

I'm a bit stuck as I can't find any help for my problem. Am I looking in the right place, is what I'm trying to do correct?
My goal is to have a private local node on which I can transfer fake funds and develop smart contracts.

Thank you for your help.

`kurtosis run github.com/ethpandaops/ethereum-package --args-file ./network_params.yaml --image-download always
`

My config file : network_params.yml
```
participants:
  - el_type: geth
    cl_type: lighthouse
    count: 2
  - el_type: geth
    cl_type: teku
network_params:
  network_id: "20240903"
additional_services:
  - dora
```
