### ISSUE TITLE
lighthouse only participant

### ISSUE THREAD

**Issue by barnabasbusa** [ethpandaops/ethereum-package#1053]
So the bug happens if there is only single lighthouse node. It will be confused as it expects at least one working peer to get started. 

You can do:

```yaml
participants:
  - count: 2
additional_services:
  - dora
```

or 

```yaml
participants:
  - cl_extra_params: ["--target-peers=0"]
additional_services:
  - dora
```
