### ISSUE TITLE
add synctest with plan.update()

### ISSUE THREAD

**Issue by barnabasbusa** [ethpandaops/ethereum-package#465]
kt run . --enclave A --args-file pre.yaml
```yaml
participants:
  - el_client_type: geth
    cl_client_type: prysm
    count: 2
```

kt run . --enclave A --args-file post.yaml
```yaml
participants:
  - el_client_type: geth
    cl_client_type: prysm  
    count: 2
 - el_client_type: geth
    cl_client_type: lighthouse
    count: 4
    validator_count: 0 ?
```
 
kt enclave A should be updated with additional nodes. 
 Think about how validators are managed.
