### ISSUE TITLE
Unexpected behavior when combining validator_count and count

### ISSUE THREAD

**Issue by 0xTylerHolmes** [ethpandaops/ethereum-package#628]
When running an enclave where we use a seperate validator client and specify the validator count, the validator_count is not honored. For example using the following configuration:
```yaml
participants:
  - el_type: reth
    cl_type: prysm
    use_seperate_vc: true
    vc_type: prysm
    validator_count: 4
    count: 2
  - el_type: nethermind
    cl_type: lodestar
    count: 2
network_params:
  num_validator_keys_per_node: 32
```

We end up with only 2 reth-prysm validators instead of 8. Additionally the logs show that we only generated 32 for each participant , perhaps this is expected but we run into the issue where validator_count doesn't equally divide `num_validator_keys_per_node`. I don't mind making a PR but I think we need to better scope the behavior of these flags. I purpose: 
1. num_validator_keys_per_node -> num_validator_keys_per_validator
    then, we set num_validators_per_node would be: num_validator_keys_per_node*validator_count. 
2. the naming convention for validators with more than one validator client becomes vc-[node-number]-[validator-number]-...

The other less ideal option is to just remove manually setting the validator_count. I'm not a fan for cases where we want to test multiple validator clients for smaller networks though.

Let me know what you think about 1 & 2, if we are happy with these I can propose a PR to address this.
