### ISSUE TITLE
Fix reth/erigon node shadowfork issues

### ISSUE THREAD

**Issue by parithosh** [ethpandaops/ethereum-package#693]
Issues to debug:
- Prysm potentially didn't work (this was only with reth, which itself seems to have and we need to validate this point)
- Reth ignoring payloads (unsure why, no newPayload comes from lighthouse)
- Erigon does some download block body thing only after the first block and then doesn't build any new blocks, unsure why this is happening either

Generic commands to speed up testing:
 ```
wget https://ethpandaops-ethereum-node-snapshots.ams3.cdn.digitaloceanspaces.com/holesky/reth/latest/_snapshot_web3_clientVersion.json
wget https://ethpandaops-ethereum-node-snapshots.ams3.cdn.digitaloceanspaces.com/holesky/reth/latest/snapshot.tar.zst
wget https://ethpandaops-ethereum-node-snapshots.ams3.cdn.digitaloceanspaces.com/holesky/reth/latest/_snapshot_eth_getBlockByNumber.json
```

Run a local server: `python3 -m http.server 65500`

Run the test:
```
participants:
  - el_type: reth
    el_image: ghcr.io/paradigmxyz/reth:v1.0.0
    cl_type: lighthouse
    el_min_mem: 16000
    el_max_mem: 24000
  - el_type: geth
    cl_type: lighthouse
network_params:
  genesis_delay: 300
  network: holesky-shadowfork
  network_sync_base_url: http://161.35.77.43:65500/
additional_services:
  - dora
snooper_enabled: true
persistent: true
```
