### ISSUE TITLE
Setting up standalone Beacon node, Validator node and Execution node.

### ISSUE THREAD

**Issue by anuprshetty** [ethpandaops/ethereum-package#807]
My understanding:
Consensus Layer (CL) (Beacon node/chain) --> responsible for PoS consensus, managing validators, finality, etc.
Validator layer (VL) --> producing blocks, attestation, etc.
Execution layer (EL) --> Executing smart contracts.

My requirement:
For learning purpose, I want to spin up below nodes or machines using kurtosis ethereum-package.
- 3 consensus layer nodes (Beacon nodes) --> Here in these 3 machines, it should be running just CL without (VL and EL).
- 4 Validator nodes --> Here in these 4 machines, it should be running just VL and EL without CL.
- 3 Execution nodes -->  Here in these 3 machines, it should be running just EL without (CL and VL).

Total = 3 CL + 4 (VL + EL) + 3 EL

For all above combination, I am using lighthouse and reth clients. And I am using docker desktop kubernetes cluster on mac.

I think the above node/machine types exists in real ethereum blockchain too. Correct me if I am wrong.

My network_params.yaml (NOTE: only necessary fields shown here):
```yaml
participants:
  - cl_type: lighthouse
    validator_count: 0
    supernode: false
    count: 3

  - vc_type: lighthouse
    vc_count: 1
    validator_count: null
    supernode: false
    el_type: reth
    use_remote_signer: false
    count: 4
    keymanager_enabled: null

  - el_type: reth
    validator_count: 0
    supernode: false
    count: 3

participants_matrix: {}

network_params:
  network: "kurtosis"
  network_id: "3151908"
  num_validator_keys_per_node: 16
  preregistered_validator_keys_mnemonic: "giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"
  preregistered_validator_count: 0

additional_services: []

wait_for_finalization: false
global_log_level: "info"
apache_port: null
keymanager_enabled: false
checkpoint_sync_enabled: false
```

Expected output:
Total = 3 CL + 4 (VL + EL) + 3 EL

Actual output:
Total = 3 (CL + EL) + 4 (CL + VL + EL) + 3 (CL + EL)

So please help me on what I am missing here.

<img width="1272" alt="kurtosis_ethereum_package_issue" src="https://github.com/user-attachments/assets/98d581ef-f063-4319-9886-31c319190ca7">
