### ISSUE TITLE
flashbots mev example

### ISSUE THREAD

**Issue by njeans** [ethpandaops/ethereum-package#866]
Hi I'm trying to run the flashbots mev example but I haven't been able to get it working. I get errors with regard to the builder getting the right block headers. There is no message in the relay about blocks being succesfully submitted.

here is my configration
```
participants:
  - el_type: geth
    cl_type: lighthouse
    count: 1
global_log_level: debug
additional_services:
  - dora
  - tx_spammer
  - blob_spammer
wait_for_finalization: false
network_params:
  deneb_fork_epoch: 1
mev_type: flashbots
```

I get many errors in rbuilder like:

`2025-01-03T03:06:50.693940Z ERROR rbuilder::live_builder::block_output::bidding::parallel_sealer_bid_maker: Error on finalize_block on ParallelSealerBidMaker block_number=486 error=FinalizeError(RootHash(AsyncStateRoot(Provider(ConsistentView(Inconsistent { tip: GotExpected { got: Some(0xf66c0d8e8f79c75d263c6d2804436dd708c8435c97daee6defbce9dbee80f343), expected: Some(0xc6d9338ad3f44df70fbc5e66ed09073d829477c697d1fa0e7e1f27d008ffc84a) } })))))`

I have also tried with `deneb_fork_epoch: 0`,  `deneb_fork_epoch: 1` and `capella_fork_epoch: 0`, and `capella_fork_epoch: 1` and  `deneb_fork_epoch: 2+`. Depending on those I get other types of errors about the builder having the wrong header or not being able to fetch the header.

I occasionally get message in the relay that a block was submitted passed the deadline when `seconds_per_slot` was lower than the default. I'm not sure if those are related.
