### ISSUE TITLE
Prysm CL panic

### ISSUE THREAD

**Issue by mempirate** [ethpandaops/ethereum-package#903]
## Context
Trying to spin up a kurtosis devnet with the following network params:
```yml
# Minimal Ethereum devnet with Geth & Prysm
# Configuration docs: https://github.com/ethpandaops/ethereum-package/blob/main/README.md#configuration

participants:
  - el_type: geth
    cl_type: prysm
    vc_type: prysm
    validator_count: 64

additional_services:
  # Network explorer
  - dora
  # Spams the network with blobs
  - blob_spammer

network_params:
  network: "kurtosis"
  network_id: "3151908"
  deposit_contract_address: "0x4242424242424242424242424242424242424242"
  seconds_per_slot: 12
  num_validator_keys_per_node: 64
  preregistered_validator_count: 64
  genesis_gaslimit: 36000000
```

After a while, the Prysm CL panics with the following trace (`kurtosis service logs ethereum-devnet cl-1-prysm-geth`)
```
[cl-1-prysm-geth] time="2025-02-12 08:46:16" level=warning msg="Sync Committee Message is too old to broadcast, discarding it" error="sync message is too late
[cl-1-prysm-geth] sync message time 2025-02-12 08:46:02 +0000 UTC (message slot 0) not within allowable range of 2025-02-12 08:46:14 +0000 UTC to 2025-02-12 08:46:16.587117517 +0000 UTC m=+39.751300743 (current slot 1)" prefix=p2p
[cl-1-prysm-geth] time="2025-02-12 08:46:16" level=error msg="Failed to find peers" error="unable to find requisite number of peers for topic /eth2/4fb725e1/sync_committee_1/ssz_snappy - only 0 out of 1 peers available after searching" prefix=p2p
[cl-1-prysm-geth] time="2025-02-12 08:46:16" level=warning msg="Sync Committee Message is too old to broadcast, discarding it" error="sync message is too late
[cl-1-prysm-geth] sync message time 2025-02-12 08:46:02 +0000 UTC (message slot 0) not within allowable range of 2025-02-12 08:46:14 +0000 UTC to 2025-02-12 08:46:16.58714685 +0000 UTC m=+39.751330034 (current slot 1)" prefix=p2p
[cl-1-prysm-geth] panic: runtime error: invalid memory address or nil pointer dereference
[cl-1-prysm-geth] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3505d70]
[cl-1-prysm-geth] 
[cl-1-prysm-geth] goroutine 4937 [running]:
[cl-1-prysm-geth] github.com/prysmaticlabs/prysm/v5/beacon-chain/forkchoice/doubly-linked-tree.(*Store).setOptimisticToInvalid(0x4000a3e000, {0x1b4da58, 0x4002672000}, {0x5b, 0x75, 0x3b, 0xec, 0x61, 0x14, 0x72, ...}, ...)
[cl-1-prysm-geth]       beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go:26 +0x50
[cl-1-prysm-geth] github.com/prysmaticlabs/prysm/v5/beacon-chain/forkchoice/doubly-linked-tree.(*ForkChoice).SetOptimisticToInvalid(0xffff37f973b8?, {0x1b4da58?, 0x4002672000?}, {0x5b, 0x75, 0x3b, 0xec, 0x61, 0x14, 0x72, ...}, ...)
[cl-1-prysm-geth]       beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go:363 +0x5c
[cl-1-prysm-geth] github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).notifyForkchoiceUpdate(0x400038e400, {0x1b4da58?, 0x4002672000?}, 0x40047fc2a0)
[cl-1-prysm-geth]       beacon-chain/blockchain/execution_engine.go:93 +0xc58
[cl-1-prysm-geth] github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).lateBlockTasks(0x400038e400, {0x1b4da58, 0x4002672000})
[cl-1-prysm-geth]       beacon-chain/blockchain/process_block.go:675 +0x9c4
[cl-1-prysm-geth] github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).runLateBlockTasks(0x400038e400)
[cl-1-prysm-geth]       beacon-chain/blockchain/process_block.go:486 +0x188
[cl-1-prysm-geth] created by github.com/prysmaticlabs/prysm/v5/beacon-chain/blockchain.(*Service).Start in goroutine 4845
[cl-1-prysm-geth]       beacon-chain/blockchain/service.go:211 +0x140
```

Not sure whether this is an issue with ethereum-package, Prysm or my config.

**Comment by parithosh** [comment]
I can confirm that I face the same issue, here's a minimal viable config that also reproduces the issue:
```
participants:
  - el_type: geth
    cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop
    vc_image: ethpandaops/prysm-validator:develop
```

I'll bring it up with the prysm team, the config looks fine on the kurtosis side
