### ISSUE TITLE
`lighthouse` can not connect due to: Error: invalid chain specs:spec MaxConsolidationRequests PerPayload

### ISSUE THREAD

**Issue by Alleysira** [ethpandaops/ethereum-package#912]
Hello, developers!

I'm using `ethereum-package` to build a testnet for Ethereum nodes testing, which is quite helpful. However, I found the consensus clients using lighthouse always fail to connect with other clients using other consensus implementation with error messages. For example, when I access dora at `localhost/clients/consensus`. There will be 2 cases:
- Only lighthouse clients can connect with lighthouse nodes, other nodes stay in `0x0000000000000000000000000000000000000000000000000000000000000000`.
- None-lighthouse clients can connect with each ohter, while lighthouse nodes stay in `0x0000000000000000000000000000000000000000000000000000000000000000`.

The error message of disconnected is:
```
Error: invalid chain specs: spec mismatch: MaxConsolidationRequests PerPayload
```

![Image](https://github.com/user-attachments/assets/bf804c20-1f23-4ce7-bccd-b1c2f7ace7d2)

I start the testnet with.
```shell
kurtosis run github.com/ethpandaops/ethereum-package --args-file ./network_params.yaml
```
This is my `network_params.yaml`.
```yaml
participants:
  - el_type: geth
    cl_type: lighthouse
    vc_type: lighthouse
    count: 2
  - el_type: geth
    cl_type: prysm
    vc_type: prysm
  - el_type: geth
    cl_type: teku
    vc_type: teku
  # 
  - el_type: besu
    cl_type: lighthouse
    vc_type: lighthouse
    count: 2
  - el_type: besu
    cl_type: prysm
    vc_type: prysm
  - el_type: besu
    cl_type: teku
    vc_type: teku
  # 
  - el_type: nethermind
    cl_type: lighthouse
    vc_type: lighthouse
    count: 2
  - el_type: nethermind
    cl_type: prysm
    vc_type: prysm
  - el_type: nethermind
    cl_type: teku
    vc_type: teku
network_params:
  network_id: "259599"
  num_validator_keys_per_node: 32
additional_services:
  - dora
```
I'm wondering how to fix this problem to build a testnet with various implementations. Thanks for your time!

**Comment by 0xalpharush** [comment]
I am also hitting this and not sure what's the cause

**Comment by GlacierWalrus** [comment]
I'm hitting this too- during debugging I noticed a couple of interesting things.

1. lighthouse uses the config `MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD`  compared to say, prysm, which uses `MaxConsolidationsRequestsPerPayload` (note the plural Consolidation**s**) but lighthouse has it right and prysm has it incorrectly pluralised[1]-  I'm not sure it matters since this is only from querying the chainspec rpc so I don't even know if it reflects a real issue.
2. The values differ- this one matters- my lighthouse beacons has this set to 1, whereas the other set it to 2. I believe 2 is correct, but I'm fairly new to this field so I don't know if that's a canonical value or simply a recommended default.

I believe this (2) is the mismatch that causes this error. I also notice that dora will connect to one set of beacons or the other- I guess whichever value it sees first, it assumes is correct.

Unfortunately I can't see a way to re-configure my lighthouse node to update the value here, as it seems to parse this from the genesis ssz on startup, so presumably I'd need to nuke my database to update it. Hopefully there's a better fix.

Maybe the best thing I can do right now is fork/rebuild dora to ignore that particular field....

[1] https://ethereum.github.io/consensus-specs/specs/electra/beacon-chain/#execution

**Comment by parithosh** [comment]
@GlacierWalrus Could you also give me a config to reproduce the issue?

@Alleysira I'm afraid i'm not able to reproduce your problem, could you please try adding `--image-download always` to your run command to pull the latest images? 

<img width="1301" alt="Image" src="https://github.com/user-attachments/assets/f5482330-8629-4349-9ba4-3ee3f5055037" />

**Comment by GlacierWalrus** [comment]
I'm still seeing this one a dora `bc70d69`/`v1.15.2` build still ftr.

@parithosh what config are you after? I'm deploying dora with the following.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dora-explorer-config
data:
  config.yml: |
    logging:
      outputLevel: "debug"

    # Chain network configuration
    chain:
      displayName: "ACME Testnet"

    # HTTP Server configuration
    server:
      host: "0.0.0.0"  # Changed from localhost to make it accessible from kubernetes
      port: "8080"

    frontend:
      enabled: true
      debug: false
      minimize: false

      siteName: "Dora the Explorer"
      siteSubtitle: ""
      
      ethExplorerLink: ""

      validatorNamesYaml: ""
      validatorNamesInventory: ""

      showSensitivePeerInfos: true
      showPeerDASInfos: true
      showSubmitDeposit: true
      showSubmitElRequests: true
      
    beaconapi:
      endpoints:
        - name: "cl-1-lighthouse-geth"
          url: "http://cl-1-lighthouse-geth.testnet.svc.cluster.local:4000"
        - name: "cl-2-prysm-erigon"
          url: "http://cl-2-prysm-erigon.testnet.svc.cluster.local:3500"
        - name: "cl-3-teku-geth"
          url: "http://cl-3-teku-geth.testnet.svc.cluster.local:4000"

      localCacheSize: 100

      redisCacheAddr: ""
      redisCachePrefix: ""

    executionapi:
      endpoints:
        - name: "el-1-geth-lighthouse"
          url: "http://el-1-geth-lighthouse.testnet.svc.cluster.local:8545"
        - name: "el-2-erigon-prysm"
          url: "http://el-2-erigon-prysm.testnet.svc.cluster.local:8545"
        - name: "el-3-geth-teku"
          url: "http://el-3-geth-teku.testnet.svc.cluster.local:8545" 

      logBatchSize: 1000
      depositDeployBlock: 0
      electraDeployBlock: 0

    indexer:
      inMemoryEpochs: 10
      activityHistoryLength: 10
      disableSynchronizer: false
      syncEpochCooldown: 2
      maxParallelValidatorSetRequests: 3

    database:
      engine: "sqlite"
      sqlite:
        file: "/app/data/explorer-db.sqlite"  # Changed to use mounted volume path

    blockDb:
      engine: "pebble"
      pebble:
        path: "/app/data/blockdb.peb"  # Changed to use mounted volume path
        cacheSize: 100 
```

Otherwise my ethereum-package config was this, but deployed using a version of kurtosis a few weeks old now:

```yaml
participants:
-
  ## EL config
  el_type: geth
  el_image: ethereum/client-go:alltools-stable
  el_extra_params: []
  el_volume_size: 400000  # 400GB in MB
  el_min_cpu: 1000        # 1 core
  el_max_cpu: 4000        # 4 cores
  el_min_mem: 1000        # 1 GB
  el_max_mem: 2000        # 2GB

  # Consensus parameters
  # cl_log_level: ''
  cl_type: lighthouse
  cl_image: sigp/lighthouse:latest
  cl_volume_size: 20480 # 20GB in MB
  cl_min_cpu: 200       # 0.2 cores
  cl_max_cpu: 1000      # 1 cores
  cl_min_mem: 500       # 0.5GB
  cl_max_mem: 2000      # 2GB
  cl_volume_size: 20480 # 20GB in MB

  # Validator client parameters
  vc_type: lighthouse
  vc_image: sigp/lighthouse:latest
  vc_min_cpu: 1000 # 1 core
  vc_max_cpu: 4000 # 4 cores
  vc_min_mem: 1000 # 1GB
  vc_max_mem: 4000 # 4GB

-
  ## EL config - Erigon full archival node
  el_type: erigon
  el_image: erigontech/erigon:v3.0.0
  el_extra_params: []
  el_volume_size: 400000  # 400GB in MB
  el_min_cpu: 1000        # 1 core
  el_max_cpu: 4000        # 4 cores
  el_min_mem: 1000        # 1 GB
  el_max_mem: 5000        # 5GB

  # Consensus parameters
  # cl_log_level: ''
  cl_type: prysm
  cl_image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
  cl_volume_size: 20480 # 20GB in MB
  cl_min_cpu: 200       # 0.2 cores
  cl_max_cpu: 1000      # 1 cores
  cl_min_mem: 500       # 0.5GB
  cl_max_mem: 2000      # 2GB
  cl_volume_size: 20480 # 20GB in MB


  # Validator client parameters
  vc_type: prysm
  vc_image: gcr.io/prysmaticlabs/prysm/validator:stable
  vc_min_cpu: 1000 # 1 core
  vc_max_cpu: 4000 # 4 cores
  vc_min_mem: 1000 # 1GB
  vc_max_mem: 4000 # 4GB

-
  # Consensus parameters
  cl_type: teku
  cl_image: consensys/teku:latest

  cl_volume_size: 20480 # 20GB in MB
  cl_min_cpu: 200       # 0.2 cores
  cl_max_cpu: 1000      # 1 cores
  cl_min_mem: 500       # 0.5GB
  cl_max_mem: 2000      # 2GB
  cl_volume_size: 20480 # 20GB in MB

  # Validator client parameters
  vc_type: teku
  vc_image: consensys/teku:latest
  vc_min_cpu: 1000 # 1 core
  vc_max_cpu: 4000 # 4 cores
  vc_min_mem: 1000 # 1GB
  vc_max_mem: 4000 # 4GB

parallel_keystore_generation: true
persistent: true
global_log_level: info
```
