### ISSUE TITLE
Blocksout on webbrowser shows nothing, any thoughts? 🙏

### ISSUE THREAD

**Issue by zouxyan** [ethpandaops/ethereum-package#920]
Just want to know how, please 🙏

I deploy it on my remote server, and visit it from local.

![Image](https://github.com/user-attachments/assets/ea46509d-39f6-47ce-a275-b4321dfca4df)

**Comment by barnabasbusa** [comment]
what are the error logs show?

**Comment by mengbin92** [comment]
I got the same one. 

blockscout logs:

![Image](https://github.com/user-attachments/assets/99e97559-2dfb-4a88-8f6b-e70deb75233d)

blocksout frontend logs:

![Image](https://github.com/user-attachments/assets/aa2bf7ae-9dbe-4c7d-a777-effeede23079)

blockscout verif logs:

![Image](https://github.com/user-attachments/assets/7fea7bee-f25f-4441-acb7-7315e883d631)

**Comment by mengbin92** [comment]
after add --image-download always, there is no errors in blockscout verif:

![Image](https://github.com/user-attachments/assets/cf46f7cc-1475-4480-941e-a8c5d7463228)

but still shows nothing:

![Image](https://github.com/user-attachments/assets/ebd4c861-4af1-4c30-b4bd-efeac3665766)

**Comment by zouxyan** [comment]
> what are the error logs show?

Strange logs on web browser console. The `172.16.0.14` is the blockscout container inner ip. 

![Image](https://github.com/user-attachments/assets/161e68bc-1d58-4df4-9261-2fb87d55f998)

**Comment by barnabasbusa** [comment]
https://github.com/ethpandaops/ethereum-package/pull/873 this might have fixed it. Can't reproduce locally. 

Can you please run with `--image-download always`?

**Comment by mengbin92** [comment]
still the same error: time out

![Image](https://github.com/user-attachments/assets/5d6635d9-5121-401b-9981-27eecc1d5499)

**Comment by barnabasbusa** [comment]
what’s the config you use?

**Comment by mengbin92** [comment]
> what’s the config you use?

```yaml
participants:
  - el_type: geth
    cl_type: lighthouse
    count: 3
network_params:
  network_id: "58585858"
  seconds_per_slot: 5
additional_services:
  - dora
  - blockscout

# Configuration place for blockscout explorer - https://github.com/blockscout/blockscout
blockscout_params:
  # blockscout docker image to use
  # Defaults to blockscout/blockscout:latest
  image: "blockscout/blockscout:latest"
  # blockscout smart contract verifier image to use
  # Defaults to ghcr.io/blockscout/smart-contract-verifier:latest
  verif_image: "ghcr.io/blockscout/smart-contract-verifier:latest"
  # Frontend image
  # Defaults to ghcr.io/blockscout/frontend:latest
  frontend_image: "ghcr.io/blockscout/frontend:latest"
```
