### ISSUE TITLE
Blockscout not working

### ISSUE THREAD

**Issue by alrevuelta** [ethpandaops/ethereum-package#994]
I'm running a similar config to [this one](https://github.com/ethpandaops/ethereum-package?tab=readme-ov-file#configuration) with just `blockscout` and `dora` as services.

However `blockscout` is not working:
* No errors are shown when running the enclave. Everything seems to start ok
```
Adding service with name 'blockscout-postgres' and image 'library/postgres:alpine'
Service 'blockscout-postgres' added with service UUID '374535128d2e46f0bd8d0c78ea06820b'

Adding service with name 'blockscout-verif' and image 'ghcr.io/blockscout/smart-contract-verifier:latest'
Service 'blockscout-verif' added with service UUID '0567f8601bfe42c7aa7312e6952c8bc9'

Adding service with name 'blockscout' and image 'blockscout/blockscout:latest'
Service 'blockscout' added with service UUID 'eece1b25d4ec4457b1af13a103455eb6'

Printing a message
Service(name="blockscout", hostname="blockscout", ip_address="redacted", ports={"http": PortSpec(number=4000, transport_protocol="TCP", application_protocol="http", wait="2m0s", url="http://blockscout:4000")})

Adding service with name 'blockscout-frontend' and image 'ghcr.io/blockscout/frontend:latest'
Service 'blockscout-frontend' added with service UUID '1c3206ec7e654615be9eb978ccfe419f'
```
* I can indeed access the frontend. But in "Latest blocks" it says "No data. Please reload the page".
* I also get a bunch of "Something went wrong. Try refreshing the page or come back later."

In case it helps, I see this in blockscout logs. That nulls maybe are wrong?
```
{"time":"2025-05-01T15:53:41.836Z","severity":"info","message":"Index already caught up.","metadata":{"fetcher":"block_catchup","last_block_number":null,"shrunk":false,"missing_block_count":0,"first_block_number":null}}
```

**Comment by barnabasbusa** [comment]
please paste your config.

**Comment by alrevuelta** [comment]
@barnabasbusa Here it is. Note the `REDACTED` in the ip. Almost all of it is copied from the example.

```
participants_matrix:
  el:
    - el_type: geth
      el_image: ethereum/client-go:v1.15.10
  cl:
    - cl_type: lighthouse
      cl_image: sigp/lighthouse:v7.0.1
    - cl_type: prysm
      cl_image: prysmaticlabs/prysm-beacon-chain:v6.0.0
      vc_image: prysmaticlabs/prysm-validator:v6.0.0

# Default configuration parameters for the network
network_params:
  # Network name, used to enable syncing of alternative networks
  # Defaults to "kurtosis"
  # You can sync any public network by setting this to the network name (e.g. "mainnet", "sepolia", "holesky", "hoodi")
  # You can sync any devnet by setting this to the network name (e.g. "dencun-devnet-12", "verkle-gen-devnet-2")
  network: "kurtosis"

  # The network ID of the network.
  network_id: "3151908"

  # The address of the staking contract address on the Eth1 chain
  deposit_contract_address: "0x00000000219ab540356cBB839Cbe05303d7705Fa"

  # Number of seconds per slot on the Beacon chain
  seconds_per_slot: 12

  # The number of validator keys that each CL validator node should get
  num_validator_keys_per_node: 64

  # This mnemonic will a) be used to create keystores for all the types of validators that we have and b) be used to generate a CL genesis.ssz that has the children
  # validator keys already preregistered as validators
  preregistered_validator_keys_mnemonic: "giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"

  # The number of pre-registered validators for genesis. If 0 or not specified then the value will be calculated from the participants
  preregistered_validator_count: 0

  # How long you want the network to wait before starting up
  genesis_delay: 20

  # The gas limit of the network set at genesis
  # Defaults to 36000000

  genesis_gaslimit: 36000000

  # Max churn rate for the network introduced by
  # EIP-7514 https://eips.ethereum.org/EIPS/eip-7514
  # Defaults to 8
  max_per_epoch_activation_churn_limit: 8

  # Churn limit quotient for the network
  # Defaults to 65536
  churn_limit_quotient: 65536

  # Ejection balance
  # Defaults to 16ETH
  # 16000000000 gwei
  ejection_balance: 16000000000

  # ETH1 follow distance
  # Defaults to 2048
  eth1_follow_distance: 2048

  # The number of epochs to wait validators to be able to withdraw
  # Defaults to 256 epochs ~27 hours
  min_validator_withdrawability_delay: 256

  # The period of the shard committee
  # Defaults to 256 epoch ~27 hours
  shard_committee_period: 256

  # The epoch at which the deneb/electra/fulu forks are set to occur. Note: PeerDAS and Electra clients are currently
  # working on forks. So set either one of the below forks.
  # Altair fork epoch
  # Defaults to 0
  altair_fork_epoch: 0

  # Bellatrix fork epoch
  # Defaults to 0
  bellatrix_fork_epoch: 0

  # Capella fork epoch
  # Defaults to 0
  capella_fork_epoch: 0

  # Deneb fork epoch
  # Defaults to 0
  deneb_fork_epoch: 0

  # Electra fork epoch
  # Defaults to 18446744073709551615
  electra_fork_epoch: 18446744073709551615

  # Fulu fork epoch
  # Defaults to 18446744073709551615
  fulu_fork_epoch: 18446744073709551615

  # Network sync base url for syncing public networks from a custom snapshot (mostly useful for shadowforks)
  # Defaults to "https://snapshots.ethpandaops.io/"
  # If you have a local snapshot, you can set this to the local url:
  # network_snapshot_url_base = "http://10.10.101.21:10000/snapshots/"
  # The snapshots are taken with https://github.com/ethpandaops/snapshotter
  network_sync_base_url: https://snapshots.ethpandaops.io/

  # Force network sync with a custom snapshot
  # This enables quicker EL sync (use with caution)
  # Defaults to false
  force_snapshot_sync: false

  # The number of data column sidecar subnets used in the gossipsub protocol
  data_column_sidecar_subnet_count: 128
  # Number of DataColumn random samples a node queries per slot
  samples_per_slot: 8
  # Minimum number of subnets an honest node custodies and serves samples from
  # Defaults to 4
  custody_requirement: 4

  # Maximum number of blobs per block for Electra fork (default 9)
  max_blobs_per_block_electra: 9
  # Target number of blobs per block for Electra fork (default 6)
  target_blobs_per_block_electra: 6
  # Base fee update fraction for Electra fork (default 5007716)
  base_fee_update_fraction_electra: 5007716

  # Maximum number of blobs per block for Fulu fork (default 12)
  max_blobs_per_block_fulu: 12
  # Target number of blobs per block for Fulu fork (default 9)
  target_blobs_per_block_fulu: 9
  # Base fee update fraction for Fulu fork (default 5007716)
  base_fee_update_fraction_fulu: 5007716

  # EIP-7732 fork epoch
  # Defaults to 18446744073709551615
  eip7732_fork_epoch: 18446744073709551615

  # EIP-7805 fork epoch
  # Defaults to 18446744073709551615
  eip7805_fork_epoch: 18446744073709551615


  # Preset for the network
  # Default: "mainnet"
  # Options: "mainnet", "minimal"
  # "minimal" preset will spin up a network with minimal preset. This is useful for rapid testing and development.
  # 192 seconds to get to finalized epoch vs 1536 seconds with mainnet defaults
  # Please note that minimal preset requires alternative client images.
  # For an example of minimal preset, please refer to [minimal.yaml](.github/tests/minimal.yaml)
  preset: "mainnet"

  # Preloaded contracts for the chain
  additional_preloaded_contracts: {}
  # Example:
  # additional_preloaded_contracts: '{
  #  "0x123463a4B065722E99115D6c222f267d9cABb524":
  #   {
  #     balance: "1ETH",
  #     code: "0x1234",
  #     storage: {},
  #     nonce: 0,
  #     secretKey: "0x",
  #   }
  # }'

  # Repository override for devnet networks
  # Default: ethpandaops
  devnet_repo: ethpandaops

  # A number of prefunded accounts to be created
  # Defaults to no prefunded accounts
  # Example:
  # prefunded_accounts: '{"0x25941dC771bB64514Fc8abBce970307Fb9d477e9": {"balance": "10ETH"}}'
  # 10ETH to the account 0x25941dC771bB64514Fc8abBce970307Fb9d477e9
  # To prefund multiple accounts, separate them with a comma
  #
  # prefunded_accounts: '{"0x25941dC771bB64514Fc8abBce970307Fb9d477e9": {"balance": "10ETH"}, "0x4107be99052d895e3ee461C685b042Aa975ab5c0": {"balance": "1ETH"}}'
  prefunded_accounts: {}

  # Maximum size of gossip messages in bytes
  # 10 * 2**20 (= 10485760, 10 MiB)
  # Defaults to 10485760 (10MB)
  max_payload_size: 10485760

  # Enable Perfect PeerDAS
  # This flag is meant to be used with 16 nodes where each node gets 8 unique columns
  # Ensure that you set the number of validator keys per node to less than or equal to 8 so that validator custody is not affected
  # Defaults to false
  perfect_peerdas_enabled: false

  # Gas limit for the network
  # Default to 0
  # If set to 0, the gas limit will be set to the default gas limit for the clients
  # Set this value to gas limit in millionths of a gwei
  # Example: gas_limit: 36000000
  # This will override the gas limit for each EL client
  # Do not confuse with genesis_gaslimit which sets the gas limit at the genesis file level
  gas_limit: 0

# Global parameters for the network

# By default includes
# - A transaction spammer & blob spammer is launched to fake transactions sent to the network
# - Forkmon for EL will be launched
# - A prometheus will be started, coupled with grafana
# - A beacon metrics gazer will be launched
# - A light beacon chain explorer will be launched
# - Default: []
additional_services:
  - blockscout
  - dora

# Global parameter to set the exit ip address of services and public ports
port_publisher:
  # if you have a service that you want to expose on a specific interface; set that IP here
  # if you set it to auto it gets the public ip from ident.me and sets it
  # Defaults to constants.PRIVATE_IP_ADDRESS_PLACEHOLDER
  # The default value just means its the IP address of the container in which the service is running
  nat_exit_ip: "REDACTED"
  # Execution Layer public port exposed to your local machine
  # Disabled by default
  # Public port start defaults to 32000
  # You can't run multiple enclaves on the same port settings
  el:
    enabled: true
    public_port_start: 42000
  # Consensus Layer public port exposed to your local machine
  # Disabled by default
  # Public port start defaults to 33000
  # You can't run multiple enclaves on the same port settings
  cl:
    enabled: true
    public_port_start: 43000
  # Validator client public port exposed to your local machine
  # Disabled by default
  # Public port start defaults to 34000
  # You can't run multiple enclaves on the same port settings
  vc:
    enabled: false
    public_port_start: 44000
  # remote signer public port exposed to your local machine
  # Disabled by default
  # Public port start defaults to 35000
  # You can't run multiple enclaves on the same port settings
  remote_signer:
    enabled: false
    public_port_start: 45000
  # Additional services public port exposed to your local machine
  # Disabled by default
  # Public port start defaults to 36000
  # You can't run multiple enclaves on the same port settings
  additional_services:
    enabled: true
    public_port_start: 46000
```
